/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  Center,
  Decal,
  useGLTF,
  useTexture,
} from "@react-three/drei";

import {
  useEffect,
  useRef,
} from "react";

export function TshirtModel({
  tshirtColor,

  designTexture,
  designTextureBack,
  designTextureLeft,
  designTextureRight,

  onViewChange,
}) {
  const {
    nodes,
    materials,
  } = useGLTF(
    "/3Dmodels/02.glb"
  );

  /*
   * ==========================================================
   * TEXTURES
   * ==========================================================
   */

  const textureFront =
    useTexture(
      designTexture ||
        "/3Dmodels/textures/design-fallback.png"
    );

  const textureBack =
    useTexture(
      designTextureBack ||
        "/3Dmodels/textures/design-fallback.png"
    );

  const textureLeft =
    useTexture(
      designTextureLeft ||
        "/3Dmodels/textures/design-fallback.png"
    );

  const textureRight =
    useTexture(
      designTextureRight ||
        "/3Dmodels/textures/design-fallback.png"
    );

  /*
   * ==========================================================
   * COLOR
   * ==========================================================
   */

  const meshRef =
    useRef(null);

  useEffect(() => {
    if (
      meshRef.current &&
      tshirtColor
    ) {
      meshRef.current
        .material
        .color
        .set(
          tshirtColor
        );
    }
  }, [tshirtColor]);

  /*
   * ==========================================================
   * VIEW CLICK
   * ==========================================================
   */

  const handleClick =
    (view) => {
      if (onViewChange) {
        onViewChange(view);
      }
    };

  return (
    <Center
      position={[
        0,
        0.1,
        0,
      ]}
    >
      <group dispose={null}>

        <group
          rotation={[
            Math.PI / 2,
            0,
            0,
          ]}
        >

          {/* =================================================
              MAIN SHIRT
          ================================================= */}

          <mesh
            scale={7.5}
            position={[
              0,
              0,
              2,
            ]}
            castShadow
            receiveShadow
            geometry={
              nodes["T-Shirt_1"]
                .geometry
            }
            material={
              materials.Shirt
            }
          />

          {/* =================================================
              FRONT
          ================================================= */}

          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["T-Shirt_2"]
                .geometry
            }
            scale={7.5}
            position={[
              0,
              0,
              2,
            ]}
            material={
              materials[
                "front.001"
              ]
            }
          >
            <meshBasicMaterial
              transparent
              opacity={0}
            />

            <Decal
              position={[
                0,
                0.2,
                -0.31,
              ]}
              rotation={[
                -Math.PI / 2 -
                  0.05,
                0,
                0,
              ]}
              scale={[
                0.52,
                0.7,
                0.5,
              ]}
              onClick={() =>
                handleClick(
                  "front"
                )
              }
            >
              <meshStandardMaterial
                map={
                  textureFront
                }
                toneMapped={
                  false
                }
                transparent
                polygonOffset
                polygonOffsetFactor={
                  -1
                }
              />
            </Decal>
          </mesh>

          {/* =================================================
              BACK
          ================================================= */}

          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["T-Shirt_3"]
                .geometry
            }
            material={
              materials.back
            }
            scale={7.5}
            position={[
              0,
              0,
              2,
            ]}
          >
            <meshBasicMaterial
              transparent
              opacity={0}
            />

            <Decal
              position={[
                0,
                -0.2,
                -0.27,
              ]}
              rotation={[
                Math.PI / 2 -
                  0.2,
                0,
                Math.PI,
              ]}
              scale={[
                0.52,
                0.7,
                0.5,
              ]}
              onClick={() =>
                handleClick(
                  "back"
                )
              }
            >
              <meshStandardMaterial
                map={
                  textureBack
                }
                toneMapped={
                  false
                }
                transparent
                polygonOffset
                polygonOffsetFactor={
                  -1
                }
              />
            </Decal>
          </mesh>

          {/* =================================================
              LEFT SLEEVE

              IMPORTANT:
              The physical mesh is opposite to the UI naming.

              So the LEFT mesh must use textureRight.
          ================================================= */}

          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["T-Shirt_4"]
                .geometry
            }
            material={
              materials[
                "left hand"
              ]
            }
            scale={7.5}
            position={[
              0,
              0,
              2,
            ]}
            onClick={() =>
              handleClick(
                "left"
              )
            }
          >
            <Decal
              position={[
                0.30,
                -0.02,
                -0.42,
              ]}
              rotation={[
                0,
                Math.PI / 2,
                0,
              ]}
              scale={[
                0.13,
                0.18,
                0.13,
              ]}
            >
              <meshStandardMaterial
                map={
                  textureRight
                }
                toneMapped={
                  false
                }
                transparent
                depthWrite={
                  false
                }
                polygonOffset
                polygonOffsetFactor={
                  -4
                }
              />
            </Decal>
          </mesh>

          {/* =================================================
              RIGHT SLEEVE

              IMPORTANT:
              The physical mesh is opposite to the UI naming.

              So the RIGHT mesh must use textureLeft.
          ================================================= */}

          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["T-Shirt_5"]
                .geometry
            }
            material={
              materials[
                "right hand"
              ]
            }
            scale={7.5}
            position={[
              0,
              0,
              2,
            ]}
            onClick={() =>
              handleClick(
                "right"
              )
            }
          >
            <Decal
              position={[
                -0.30,
                -0.02,
                -0.42,
              ]}
              rotation={[
                0,
                -Math.PI / 2,
                0,
              ]}
              scale={[
                0.13,
                0.18,
                0.13,
              ]}
            >
              <meshStandardMaterial
                map={
                  textureLeft
                }
                toneMapped={
                  false
                }
                transparent
                depthWrite={
                  false
                }
                polygonOffset
                polygonOffsetFactor={
                  -4
                }
              />
            </Decal>
          </mesh>

        </group>

        {/* =================================================
            SHIRT COLOR
        ================================================= */}

        <group
          rotation={[
            Math.PI / 2,
            0,
            0,
          ]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "T-Shirt001"
              ].geometry
            }
            material={
              materials.background
            }
            scale={7.5}
            position={[
              0,
              0,
              2,
            ]}
            ref={
              meshRef
            }
          />
        </group>

      </group>
    </Center>
  );
}

useGLTF.preload(
  "/3Dmodels/02.glb"
);